#[context.production.environment]

[build.environment]
  NODE_VERSION = "18.19.0"
  YARN_VERSION = "1.22.21"
  YARN_FLAGS = "--ignore-engines"

# A basic redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
